act1 = Activity.create(teacher_id: 1, camp_id:2, skill_id:1, date: "2018-01-01")
act2 = Activity.create(teacher_id: 2, camp_id:1, skill_id:2, date: "2018-07-06")
act3 = Activity.create(teacher_id: 3, camp_id:3, skill_id:5, date: "2018-10-01")
act4 = Activity.create(teacher_id: 4, camp_id:2, skill_id:1, date: "2018-04-01")
act5 = Activity.create(teacher_id: 5, camp_id:2, skill_id:1, date: "2018-01-04")
act5 = Activity.create(teacher_id: 6, camp_id:3, skill_id:4, date: "2018-03-01")
skill1 = Skill.create(name: 'surfing', category: 'water')
skill2 = Skill.create(name: 'rock climbing', category: 'vertical')
skill3 = Skill.create(name: 'swimming', category: 'water')
skill4 = Skill.create(name: 'hiking', category: 'land')
skill5 = Skill.create(name: 'skiing', category: 'snow')
camp1 = Camp.create(name: "Karstaway", location: 'Guilin')
camp2 = Camp.create(name: "Jalenboo", location: 'Wanning')
camp3 = Camp.create(name: "Le Ski", location: 'Beijing', )
CampSkill.create(skill_id: 1, camp_id: 2)
CampSkill.create(skill_id: 3, camp_id: 2)
CampSkill.create(skill_id: 2, camp_id: 1)
CampSkill.create(skill_id: 3, camp_id: 1)
CampSkill.create(skill_id: 4, camp_id: 2)
CampSkill.create(skill_id: 4, camp_id: 1)
CampSkill.create(skill_id: 5, camp_id: 3)
teach1 = Teacher.create(name:"Sally")
teach2 = Teacher.create(name:"Steve")
teach3 = Teacher.create(name:"Victor")
teach4 = Teacher.create(name:"Lou")
teach5 = Teacher.create(name:"Sam")
teach6 = Teacher.create(name:"Bob")
TeacherSkill.create(teacher_id:1, skill_id:1)
TeacherSkill.create(teacher_id:2, skill_id:1)
TeacherSkill.create(teacher_id:1, skill_id:3)
TeacherSkill.create(teacher_id:3, skill_id:3)
TeacherSkill.create(teacher_id:4, skill_id:2)
TeacherSkill.create(teacher_id:4, skill_id:5)
TeacherSkill.create(teacher_id:1, skill_id:4)
TeacherSkill.create(teacher_id:6, skill_id:1)
TeacherSkill.create(teacher_id:5, skill_id:1)
student1 = Student.create(name: 'Lucy', camp_id:1)
student2 = Student.create(name: 'Jon', camp_id:1)
student3 = Student.create(name: 'Ben', camp_id:2)
student4 = Student.create(name: 'Shawn', camp_id:3)
student5 = Student.create(name: 'Dan', camp_id:3)
StudentActivity.create(student_id:5, activity_id:1)
